---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
      app: postgres
  template:
    metadata:
      labels:
        service: postgres
        app: postgres
    spec:
      containers:
        - name: postgres
          image: joatmon08/nyc311-database
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: nyc
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password