---
# Service to expose web frontend

apiVersion: v1
kind: Service
metadata:
  name: nyc
spec:
  selector:
    app: nyc
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

---
# Service account to allow pod access to Vault via K8s auth

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nyc
automountServiceAccountToken: true

---
# Web frontend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyc
  labels:
    app: nyc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nyc
  template:
    metadata:
      labels:
        app: nyc
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "nyc"
        vault.hashicorp.com/namespace: "admin"
        vault.hashicorp.com/agent-inject-secret-config: "database/creds/nyc"
        vault.hashicorp.com/agent-inject-template-config: |
          {
            "bind_address": ":9090",
          {{ with secret "database/creds/web" -}}
            "db_connection": "host=postgres port=5432 user={{ .Data.username }} password={{ .Data.password }} dbname=products sslmode=disable"
          {{- end }}
          }
    spec:
      serviceAccountName: web
      containers:
        - name: web
          image: nicholasjackson/vault-demo-app:v0.0.1
          ports:
            - containerPort: 9090
          env:
            - name: "CONFIG_FILE"
              value: "/vault/secrets/config"